### ISSUE TITLE
How to handle query variables?

### ISSUE THREAD

**Issue by Hamid313-coder** [ihorbokov/graphql_2_rest#2]
Some queries have some variables, which should passed to the query. So how to handle that?

```
mutation DesktopSignUp($inputUser: InputUser!) {
  desktopSignUp(inputUser: $inputUser) {
    statusCode
    message
    userId
    token
    tokenExpiration
  }
}
```

like the above snippet.
the InputUser is a Map<String, dynamic> which has lots of key values.

**Comment by ihorbokov** [comment]
Hello @Hamid313-coder! Hope v2.0.0 of the library will solve this issue 👍
